---

- name: "Debian: Add repo.mongodb.org repository GPG key"
  apt_key:
    url: "{{ mongodb__apt_keyurl }}"
    state: present
  when: not mongodb__apt_localkey

- name: "Debian: Add local repository GPG key"
  apt_key:
    data: "{{ lookup('file', 'server-'+ mongodb__version +'.asc') }}"
    state: present
  when: mongodb__apt_localkey

- name: "Debian: Configure repo.mongodb.org apt repository"
  apt_repository:
    repo: "{{ mongodb__apt_repo[ ansible_distribution ] }}"
    state: present
    update_cache: yes

- name: "Debian: Install mongodb packages"
  apt:
    name: "{{ mongodb__packages }}"
    state: present
    update_cache: yes
