---
# handlers file for mongodb

- name: restart mongodb-server
  become: yes
  service: name=mongod state=restarted

- name: reload mongodb-server
  become: yes
  service: name=mongod state=reloaded
